[package]
name = "screeps-dashboard-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
dotenvy = "0.15.7"
futures = "0.3.31"
plotters = "0.3.7"
screeps-rust-api = "0.1.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = {version = "1.48.0", features = ["full"]}
